// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web.Data;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(WelfareDb))]
    [Migration("20251204220120_AddedNullInRecieverToTransaction")]
    partial class AddedNullInRecieverToTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web.Models.AdminLogin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("AdminLogins");
                });

            modelBuilder.Entity("web.Models.DonorToWelfareTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("ClothesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClothesType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FemaleClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int?>("FemaleClothesQuantity")
                        .HasColumnType("int");

                    b.Property<string>("FoodDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FoodInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int?>("FoodQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KidsClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int?>("KidsClothesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MaleClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int?>("MaleClothesQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("MonetaryAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ShelterBeds")
                        .HasColumnType("int");

                    b.Property<string>("ShelterDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WelfareBalanceAfter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("TransactionId");

                    b.HasIndex("DonorUserId");

                    b.ToTable("DonorToWelfareTransactions");
                });

            modelBuilder.Entity("web.Models.MonthlyAllocationLog", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FemaleClothesAllocated")
                        .HasColumnType("int");

                    b.Property<int>("FemaleClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int>("FemaleClothesInventoryBefore")
                        .HasColumnType("int");

                    b.Property<int>("FoodAllocated")
                        .HasColumnType("int");

                    b.Property<int>("FoodInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int>("FoodInventoryBefore")
                        .HasColumnType("int");

                    b.Property<string>("FoodUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KidsClothesAllocated")
                        .HasColumnType("int");

                    b.Property<int>("KidsClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int>("KidsClothesInventoryBefore")
                        .HasColumnType("int");

                    b.Property<int>("MaleClothesAllocated")
                        .HasColumnType("int");

                    b.Property<int>("MaleClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int>("MaleClothesInventoryBefore")
                        .HasColumnType("int");

                    b.Property<decimal>("MoneyAllocated")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllocationId");

                    b.ToTable("MonthlyAllocationLogs");
                });

            modelBuilder.Entity("web.Models.NGOToWelfareTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("ClothesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClothesSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClothesType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorNgoId")
                        .HasColumnType("int");

                    b.Property<int?>("FemaleClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int?>("FemaleClothesQuantity")
                        .HasColumnType("int");

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FoodInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int?>("FoodQuantity")
                        .HasColumnType("int");

                    b.Property<string>("FoodUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KidsClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int?>("KidsClothesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MaleClothesInventoryAfter")
                        .HasColumnType("int");

                    b.Property<int?>("MaleClothesQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("MonetaryAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ShelterBeds")
                        .HasColumnType("int");

                    b.Property<string>("ShelterDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WelfareBalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionId");

                    b.HasIndex("DonorNgoId");

                    b.ToTable("NGOToWelfareTransactions");
                });

            modelBuilder.Entity("web.Models.NGOsLogin", b =>
                {
                    b.Property<int>("NgoId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NgoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NGOsLogins");
                });

            modelBuilder.Entity("web.Models.ReceiverRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClothesType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamilyMembers")
                        .HasColumnType("int");

                    b.Property<int?>("FemaleClothesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("FoodQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FulfilledDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KidsClothesQuantity")
                        .HasColumnType("int");

                    b.Property<string>("LoanPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaleClothesQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("RepaymentMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RequiredRooms")
                        .HasColumnType("int");

                    b.Property<int?>("ShelterDurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("ReceiverRequests");
                });

            modelBuilder.Entity("web.Models.UserLoginConfidentials", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("CNIC")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserLoginConfidentials");
                });

            modelBuilder.Entity("web.Models.WelfareFund", b =>
                {
                    b.Property<int>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FundId"));

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FemaleClothesInventory")
                        .HasColumnType("int");

                    b.Property<int>("FoodInventoryUnits")
                        .HasColumnType("int");

                    b.Property<string>("FoodUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KidsClothesInventory")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMonthlyReset")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaleClothesInventory")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyAllocation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthlyFemaleClothesAllocation")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyFoodAllocation")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyKidsClothesAllocation")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyMaleClothesAllocation")
                        .HasColumnType("int");

                    b.Property<int>("ShelterAvailable")
                        .HasColumnType("int");

                    b.Property<int>("ShelterCapacity")
                        .HasColumnType("int");

                    b.Property<int>("ShelterOccupied")
                        .HasColumnType("int");

                    b.HasKey("FundId");

                    b.ToTable("WelfareFunds");

                    b.HasData(
                        new
                        {
                            FundId = 1,
                            CurrentBalance = 1000000m,
                            FemaleClothesInventory = 1000,
                            FoodInventoryUnits = 100000,
                            FoodUnit = "rations",
                            KidsClothesInventory = 500,
                            LastMonthlyReset = new DateTime(2025, 12, 5, 3, 1, 10, 737, DateTimeKind.Local).AddTicks(7732),
                            LastUpdated = new DateTime(2025, 12, 5, 3, 1, 10, 737, DateTimeKind.Local).AddTicks(7710),
                            MaleClothesInventory = 1000,
                            MonthlyAllocation = 1000000m,
                            MonthlyFemaleClothesAllocation = 500,
                            MonthlyFoodAllocation = 50000,
                            MonthlyKidsClothesAllocation = 300,
                            MonthlyMaleClothesAllocation = 500,
                            ShelterAvailable = 50,
                            ShelterCapacity = 50,
                            ShelterOccupied = 0
                        });
                });

            modelBuilder.Entity("web.Models.WelfareToNGORequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FemaleClothesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("FoodQuantity")
                        .HasColumnType("int");

                    b.Property<string>("FoodUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FulfilledAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FulfilledDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FulfilledFemaleClothes")
                        .HasColumnType("int");

                    b.Property<int?>("FulfilledFoodQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("FulfilledKidsClothes")
                        .HasColumnType("int");

                    b.Property<int?>("FulfilledMaleClothes")
                        .HasColumnType("int");

                    b.Property<int?>("FulfilledShelterBeds")
                        .HasColumnType("int");

                    b.Property<int?>("KidsClothesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MaleClothesQuantity")
                        .HasColumnType("int");

                    b.Property<int>("NgoId")
                        .HasColumnType("int");

                    b.Property<string>("NgoResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShelterBeds")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("AdminId");

                    b.HasIndex("NgoId");

                    b.ToTable("WelfareToNGORequests");
                });

            modelBuilder.Entity("web.Models.WelfareToReceiverTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int?>("ApprovedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FemaleClothesProvided")
                        .HasColumnType("int");

                    b.Property<int?>("FoodUnitsProvided")
                        .HasColumnType("int");

                    b.Property<int?>("KidsClothesProvided")
                        .HasColumnType("int");

                    b.Property<string>("LoanPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaleClothesProvided")
                        .HasColumnType("int");

                    b.Property<decimal>("MonetaryAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MonthlyRepaymentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("RepaymentMonths")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomsAllocated")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShelterEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShelterStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WelfareBalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionId");

                    b.HasIndex("ApprovedByAdminId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("RequestId");

                    b.ToTable("WelfareToReceiverTransactions");
                });

            modelBuilder.Entity("web.Models.DonorToWelfareTransaction", b =>
                {
                    b.HasOne("web.Models.UserLoginConfidentials", "Donor")
                        .WithMany("DonorTransactions")
                        .HasForeignKey("DonorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("web.Models.NGOToWelfareTransaction", b =>
                {
                    b.HasOne("web.Models.NGOsLogin", "DonorNgo")
                        .WithMany("NGOTransactions")
                        .HasForeignKey("DonorNgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonorNgo");
                });

            modelBuilder.Entity("web.Models.ReceiverRequest", b =>
                {
                    b.HasOne("web.Models.UserLoginConfidentials", "Receiver")
                        .WithMany("ReceiverRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("web.Models.WelfareToNGORequest", b =>
                {
                    b.HasOne("web.Models.AdminLogin", "Admin")
                        .WithMany("NGORequests")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web.Models.NGOsLogin", "Ngo")
                        .WithMany("WelfareRequests")
                        .HasForeignKey("NgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Ngo");
                });

            modelBuilder.Entity("web.Models.WelfareToReceiverTransaction", b =>
                {
                    b.HasOne("web.Models.AdminLogin", "ApprovedByAdmin")
                        .WithMany("ReceiverApprovals")
                        .HasForeignKey("ApprovedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("web.Models.UserLoginConfidentials", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web.Models.ReceiverRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByAdmin");

                    b.Navigation("Receiver");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("web.Models.AdminLogin", b =>
                {
                    b.Navigation("NGORequests");

                    b.Navigation("ReceiverApprovals");
                });

            modelBuilder.Entity("web.Models.NGOsLogin", b =>
                {
                    b.Navigation("NGOTransactions");

                    b.Navigation("WelfareRequests");
                });

            modelBuilder.Entity("web.Models.UserLoginConfidentials", b =>
                {
                    b.Navigation("DonorTransactions");

                    b.Navigation("ReceiverRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
